### PR TITLE
Add new folder for templates and a new AWS CloudFormation template for testing REST Adapter Service.

### PR DESCRIPTION
**Pull request by petkivim**
Add new folder for templates and a new subfolder for AWS CloudFormation
templates.

Add new CloudFormation template for testing X-Road REST Adapter Service
in AWS. The template creates a VPC and adds an EC2 instance with an
Elastic IP address and a security group. After that the latest version
of REST Adapter Service is fetched from GitHub, compiled and started.

### CODE REVIEW

**Comment by hanhaka** [comment]
New ticket created into Palveluväylä dev backlog for reviewing this PR. Work estimate to complete the ticket will be done in near future and actual review work starts after that.

**Comment by hanhaka** [comment]
Hi,

thanks for the PR. Development team checked trough the files and we had a discussion about how to handle this one.

Some comments: 
- maintaining the cloudformation stack adds some work to the development of adapter. E.g. we have to test that stack works with new versions of adapter 
- is the cloudformation stack part of "core" rest adapter features? Possibly not, and we should be vary of feature creep. Rest adapter project is already quite many-faceted as is. 
- for clients who use AWS, the stack might not be suitable for their AWS environment. For example, in our environment we would like to grant access to HTTP:8080 based on a security group, not an IP range. For the server IP, we would rather use auto assigned private IP and not give the server public IP at all. Some other details may be uncomfortable for other clients in regard to their AWS environment conventions. 
- for clients who do not use AWS, the stack is not usable. Is it correct for us to support AWS, but not Azure or Google Cloud? 
(- 8080 port should ideally be configurable) 

To summarize: 
- We prefer that this PR is not included as a core part of REST Service Adapter due to reasons mentioned above.
- However, since the AWS is quite widely used we could publish the template & short readme as an example how the AWS could be configured to work with REST Adapter Service. The template might be beneficial for some users dealing with AWS and REST adapter so why not to publish it.
- To make sure that there is no misunderstanding or presumptions of AWS template functionality, it must be stated both in readme.md and in AWS CloudFormation template description that the template is NOT officially supported by REST Service Adapter: it is only an example of how AWS could be used with REST Service Adapter. Also, it must be stated that it is not guaranteed that every version of REST Adapter Service will work with this AWS template and in the case of issues, the development team is not able to give support for resolving the issues.

Could you add the mentioned statements into your PR's files? 
It can be approved after these changes done.

Thanks,
Hannu

**Comment by petkivim** [comment]
Hi,

Thank you for the feedback. I agree with you that templates like this should not be part of the core. However, I think they are useful for new users as they help you to get the service up and running and ready for use in minutes.   It would be great to have templates for all the major cloud platforms and not just for AWS. Maybe more PRs will arrive from other users. :)

I’ve done the proposed changes and added a new ```ServerPort``` parameter for defining the port number. Unfortunately, it is not possible to use an existing security group, because security groups belong to a VPC and in this case a new VPC is created for REST Adapter Service.

Regards,
Petteri

**Review by hanhaka — APPROVED** [review]

**Review by hanhaka — COMMENTED** [review]
Looks good.

**Pull request merged**
